apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  namespace: argocd
spec:
  destination:
    namespace: rollouts-demo
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: "https://github.com/argoproj/argo-rollouts"
      path: apps/rollouts-demo
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true