apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-analysis
  namespace: rollouts-demo
spec:
  args:
  - name: ingress-name
  metrics:
  - name: success-rate
    interval: 1m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.prometheus:9090
        query: |
          sum(rate(nginx_ingress_controller_requests{ingress=~"{{args.ingress-name}}", status!~"[4-5].*"}[1m])) /
          sum(rate(nginx_ingress_controller_requests{ingress=~"{{args.ingress-name}}"}[1m]))