apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-analysis
  namespace: rollouts-demo
spec:
  args:
  - name: ingress-name
  - name: namespace
  metrics:
  - name: success-rate
    interval: 2m
    successCondition: result[0] >= 95.00
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.prometheus:9090
        query: |
          sum(rate(nginx_ingress_controller_requests{namespace="{{args.namespace}}", ingress="{{args.ingress-name}}", status!~"[4-5].*"}[2m])) /
          sum(rate(nginx_ingress_controller_requests{namespace="{{args.namespace}}", ingress="{{args.ingress-name}}"}[2m])) * 100
