apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.10/manifests/install.yaml
  - namespace.yaml
  # - service-monitor.yaml # uncomment to enable prometheus service monitor after installing kube-prometheus-stack
patches:
  - path: argocd-server.yaml
    target:
      kind: Deployment
      name: argocd-server